version: "3.3"

services:
  redis-server:
    image: "redis"
  api:
    build: .
    container_name: cache-image-c
    ports:
      - "4000:4000"
    volumes:
      - /home/piyal/Desktop/twurs/redis-testing:/app
      - /app/node_modules
